# Copyright (C) 2021 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
version: '3'

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'lint'
      - task: 'test'
    desc: 'Run all CI-related tasks'

  clean:
    cmds:
      - 'rm -fr vendor composer.lock'
    desc: 'Delete all third-party dependencies and lock files'

  dependencies:
    cmds:
      - task: 'dependencies:php'
    desc: 'Run all dependency-installing-related tasks'

  dependencies:php:
    cmds:
      - 'composer install --no-ansi --no-interaction --no-progress'
    desc: 'Install PHP dependencies'

  lint:
    cmds:
      - task: 'lint:php'
    desc: 'Run all linting-related tasks'

  lint:php:
    cmds:
      - 'vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff'
    desc: 'Lint PHP files with PHP Coding Standards Fixer'

  test:
    cmds:
      - task: 'test:php'
    desc: 'Run all testing-related tasks'

  test:php:
    cmds:
      - 'vendor/bin/phpunit --testdox'
    desc: 'Run PHP tests with PHPUnit'
