# Copyright (C) 2019-2021 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
version: 2

output: 'prefixed'

tasks:
  default:
    deps:
      - task: 'ci'

  ci:
    cmds:
      - task: 'clean'
      - task: 'dependencies'
      - task: 'lint'
    desc: 'Run all CI-related tasks'

  clean:
    cmds:
      - 'rm -fr node_modules package-lock.json'
    desc: 'Delete all third-party dependencies and lock files'

  dependencies:
    cmds:
      - task: 'dependencies:javascript'
    desc: 'Run all dependency-installing-related tasks'

  dependencies:javascript:
    cmds:
      - 'npm install'
    env:
      CI: true
    desc: 'Install JavaScript dependencies'

  lint:
    cmds:
      - task: 'lint:javascript'
    desc: 'Run all linting-related tasks'

  lint:javascript:
    cmds:
      - "node_modules/.bin/eslint bin/yassg src/**"
    desc: 'Lint JavaScript files with ESLint'
