# Copyright (C) 2021 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
name: 'Lint, Analyse, and Test Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint-analyse-and-test:
    name: 'Lint, analyse, and test project'
    runs-on: 'ubuntu-20.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'

      - name: 'Set up PHP environment'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '8.0'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Download project dependencies and run all linting, static analysis, and testing tasks'
        run: './bin/task ci'
