# Copyright (C) 2021 Damien Dart, <damiendart@pobox.com>.
# This file is distributed under the MIT licence. For more information,
# please refer to the accompanying "LICENCE" file.

---
name: 'Lint Project'

on:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: 'Lint project'
    runs-on: 'ubuntu-18.04'
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v2'

      - name: 'Set up Node environment'
        uses: 'actions/setup-node@v2-beta'
        with:
          node-version: '14'

      - name: 'Install Task'
        run: 'curl -sL https://taskfile.dev/install.sh | sh'

      - name: 'Download project dependencies and run all linting-related tasks'
        run: './bin/task ci'
